### ISSUE TITLE
Game shows congtrats screen before completing the minigame

### ISSUE THREAD

**Issue by AkiKurvinen** [brylie/language-lesson-chat#33]
After completing the discussion the game goes forward before player completes the minigame.
I expected the congrats screen to appear only after completing the minigame.

**Comment by brylie** [comment]
On looking at this issue, we don't currently have minigame completion tracking. So, it's easier to just move the minigames to the success page for the time being.

**Comment by brylie** [comment]
Later, we can add an issue to track the completion of the minigames.

**Comment by brylie** [comment]
I've merged some changes that now display the minigames list on the chat summary page under the "practice more" section:

![Screenshot 2024-09-08 at 15 32 00](https://github.com/user-attachments/assets/126eb002-693c-4edb-9266-04a913ef4dcd)
